### PR TITLE
fix(input/#2926): Part 1 - Fix windows UTF-16 / UTF-8 conversion for key presses

### LINKED ISSUE #2926: Bug: Some keyboard keys not working properly
Version: 0.5.9-nightly | 8a1739e
Platform: Windows

In oni, when I press the "é" keys, Oni exists.

The debug output is :
```
[INFO]  [10.421s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: xE9
 WithShift: 2
 WithAltGr: (none)
 WithAltGrShift: (none)
[INFO]  [10.421s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: xE9
 WithShift: 2
 WithAltGr: (none)
 WithAltGrShift: (none)
[INFO]  [10.421s] Oni2.Store.dispatch : dispatch: KeyDown {
  key =
  (KeyPress.PhysicalKey
     { PhysicalKey.key = (Key.Character '\233');
       modifiers =
       { Modifiers.control = false; alt = false; altGr = false;
         shift = false; meta = false }
       });
  scancode = 31; time = <opaque>}
```

I have this issue only in nightly (in stable, it works correctly)

PS : I have another strange behaviour with another keys. When I press the right arrow, the cursor move to the beginning of the buffer.

```
[INFO]  [26.210s] Oni2.Store.dispatch : dispatch: KeyDown {
  key =
  (KeyPress.PhysicalKey
     { PhysicalKey.key = Key.PageUp;
       modifiers =
       { Modifiers.control = false; alt = false; altGr = false;
         shift = false; meta = false }
       });
  scancode = 79; time = <opaque>}
[DEBUG] [26.211s] Oni2.Store.dispatch : After: KeyDown {
  key =
  (KeyPress.PhysicalKey
     { PhysicalKey.key = Key.PageUp;
       modifiers =
       { Modifiers.control = false; alt = false; altGr = false;
         shift = false; meta = false }
       });
  scancode = 79; time = <opaque>}
[DEBUG] [26.211s] Oni2.Store.StoreThread : Running effect: Batch:
 input.immediateDispatch

[INFO]  [26.211s] Oni2.Store.dispatch : dispatch: KeyboardInput {isText = false; input = "<PAGEUP>"}
[DEBUG] [26.212s] Oni2.Store.dispatch : After: KeyboardInput {isText = false; input = "<PAGEUP>"}
[INFO]  [26.212s] Oni2.Store.dispatch : dispatch: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "<PAGEUP>")))
[DEBUG] [26.213s] Oni2.Store.dispatch : After: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "<PAGEUP>")))
```

### PR DESCRIPTION
**Pull request by bryphe**
__Issue:__ Typing a Unicode character on Windows would fail, causing a crash.

__Defect:__ The character was being encoded as UTF-16, but we were expecting UTF-8. When we went to unpack the character as UTF-8, Zed would throw an exception, since the binary data was not a valid UTF-8 character.

__Fix:__ Convert from UTF16 to UTF8 prior to sending back to OCaml.

Fixes #2926

__Todo:__
- [x] Add test case
- [x] Add CHANGES entry

### CODE REVIEW

File: src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c [hunk 1]
```diff
@@ -101,15 +129,16 @@ void characterForNativeCode(
...
 
   if (count == -1) {
     keyboardState[VK_SHIFT] = 0x0;
     keyboardState[VK_MENU] = 0x0;
     keyboardState[VK_CONTROL] = 0x0;
 
+    // Doesn't look like this is used?
     UINT spaceKeycode = MapVirtualKeyEx(SPACE_SCAN_CODE, MAPVK_VSC_TO_VK, keyboardLayout);
-    ToUnicodeEx(spaceKeycode, SPACE_SCAN_CODE, keyboardState, dest, 5, 0, keyboardLayout);
+    // ToUnicodeEx(spaceKeycode, SPACE_SCAN_CODE, keyboardState, dest, 5, 0, keyboardLayout);
```
Comment (bryphe) [inline src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c:141]: @zbaylin - do you happen to know why this `MapVirtualKeyEx`/`ToUnicodeEx` call is needed? It seems like it isn't used based on the `dest[0] = '\0'` below - but wanted to double-check before I removed.

Comment (zbaylin) [reply src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c:141]: I actually don't know -- IIRC I copied that from the atom repo. Your intuition seems correct to me though

Comment (bryphe) [reply src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c:141]: Ah, cool - thanks @zbaylin !
